#:schema node_modules/wrangler/config-schema.json
name = "wallaby-web"
compatibility_date = "2026-04-01"
main = "worker/router.js"

workers_dev = false
preview_urls = false

[version_metadata]
binding = "CF_VERSION_METADATA"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "wallaby-web"

[[d1_databases]]
binding = "GUESTS_DB"
database_name = "wallabyfest-guests-preview"
database_id = "e051dc73-8940-4dcc-b670-572c94d0bd07"

[vars]
LOG_LEVEL = "debug"
CF_ACCOUNT_ID = "890cec1351da5724fac94ef095c16a24"
CF_ACCESS_POLICY_ID = "fbaa0a6f-7900-45fe-8dca-04bb1ef98a04"

[build]
command = "npm run build"
watch_dir = "site"

[assets]
directory = "dist"
not_found_handling = "404-page"

[observability.logs]
enabled = true
invocation_logs = true

# Production Env
[env.production]
workers_dev = false
preview_urls = false

[env.production.vars]
LOG_LEVEL = "info"
CF_ACCOUNT_ID = "890cec1351da5724fac94ef095c16a24"
CF_ACCESS_POLICY_ID = "8ce75a5b-12b4-4014-82e6-723e9aee43e8"

[env.production.version_metadata]
binding = "CF_VERSION_METADATA"

[[env.production.r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "wallaby-web"

[[env.production.routes]]
pattern = "wallabyfest.co.uk"
custom_domain = true

[[env.production.d1_databases]]
binding = "GUESTS_DB"
database_name = "wallabyfest-guests"
database_id = "fc8fca57-d92e-40c7-85a6-0459263f4fef"

# Preview Env
[env.preview]
workers_dev = true
preview_urls = true

[env.preview.version_metadata]
binding = "CF_VERSION_METADATA"

[[env.preview.r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "wallaby-web"

[env.preview.vars]
LOG_LEVEL = "debug"
CF_ACCOUNT_ID = "890cec1351da5724fac94ef095c16a24"
CF_ACCESS_POLICY_ID = "fbaa0a6f-7900-45fe-8dca-04bb1ef98a04"

[[env.preview.d1_databases]]
binding = "GUESTS_DB"
database_name = "wallabyfest-guests-preview"
database_id = "e051dc73-8940-4dcc-b670-572c94d0bd07"
