#:schema node_modules/wrangler/config-schema.json
name = "wallaby-web"
compatibility_date = "2026-04-01"
main = "worker.js"

workers_dev = true

[build]
command = "npm run build"

[[routes]]
pattern = "wallabyfest.co.uk"
custom_domain = true

[assets]
directory = "dist"
not_found_handling = "404-page"

[[d1_databases]]
binding = "wallabyfest_guests"
database_name = "wallabyfest-guests"
database_id = "fc8fca57-d92e-40c7-85a6-0459263f4fef"
