name: Lint & Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - run: npm ci

      - run: npm run lint
      
      - run: npm test
